- default:
  - Blog: http://stevejohnson.posterous.com/
  - tim|steve: http://timunionsteve.posterous.com/
  - Music: music
  - CWRU Hacker Society: http://goto.case.edu/
  - Python Game Tutorial/Python Game Programming Tutorial: pyglettutorial
    pages: 6
  - Start Making Games: http://stevejohnson.posterous.com/a-starting-point-for-making-games

- hidden:
  - Hacker Résumé: hacker_resume

- Toys:    
  - Art Project 1: art_project_1
  - Artack: artack
  - Bungie Chopper/Elite Bungie Chopper Squadron: bungie_chopper
  - gw0rp: gw0rp
  - Escort Wing: escort_wing
  - Splatterboard: splatterboard

- Code:  
  - JTrie: http://www.github.com/irskep/jtrie
  - MRJob Py3k port: http://www.github.com/irskep/mrjob/tree/py3k
  - Regex compiler: http://www.github.com/irskep/regex_compiler
  - T-Reg: http://www.github.com/irskep/T-Reg

- Social:
  - Résumé: resume
  - Stack Overflow CV: http://careers.stackoverflow.com/stevejohnson
  - Twitter: http://www.twitter.com/irskep
  - Stack Overflow: http://stackoverflow.com/users/8061/steve-johnson
  - Hacker News: http://news.ycombinator.com/user?id=stevejohnson
